apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pushgateway
  namespace: devtoolv2
spec:
  serviceName: pushgateway-svc
  replicas: 1
  selector:
    matchLabels:
      name: pushgateway
  template:
    metadata:
      labels:
        name: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: 10.10.102.213:8443/cloudnevro/pushgateway:v1.0.0-nopersist
          imagePullPolicy: Always
          args:
            - "--metric.expire.interval=60s --metric.expire.remove.interval=1h"
          resources:
            requests:
              cpu: "300m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "100Mi"
          ports:
            - name: http
              containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pushgateway
  name: pushgateway-svc
  namespace: devtoolv2
spec:
  ports:
    - name: port1
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    name: pushgateway
  type: ClusterIP

