apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pushgateway
  namespace: devtool
spec:
  serviceName: pushgateway-cluster-svc
  replicas: 1
  selector:
    matchLabels:
      name: pushgateway
  template:
    metadata:
      labels:
        name: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: pushgateway:v1.0.0-amd
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "200Mi"
          ports:
            - name: http
              containerPort: 9091

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pushgateway
  name: pushgateway-svc
  namespace: devtool
spec:
  ports:
    - name: port1
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    name: pushgateway
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pushgateway
  name: pushgateway-cluster-svc
  namespace: devtool
spec:
  clusterIP: None
  ports:
    - name: port1
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    name: pushgateway
  type: ClusterIP

---
